title: voxxel.ai
description: Log of Computer Vision Applications for the real world after the AI agent madness.
author: blusa
theme: minima

# Dominio completo del sitio
url: "https://voxxel.ai"

# No estás usando subcarpeta, así que esto queda vacío
baseurl: ""

# Permite paginar tus entradas (ej: 5 por página)
paginate: 5
paginate_path: "/page:num"

# Activa el plugin de paginación
plugins:
  - jekyll-paginate

# Si en el futuro tenés assets como imágenes o scripts, estos te ayudan
markdown: kramdown
highlighter: rouge

# Utterances comments configuration
utterances:
  repo: "blusa/blusa.github.io"  # Replace with your GitHub username/repository-name
  issue_term: "pathname"  # Maps comments to posts by pathname
  theme: "github-light"   # Options: github-light, github-dark, preferred-color-scheme, etc.

# Minima theme settings
minima:
  # Exclude pages from navigation
  header_pages:
    - index.html
